### ISSUE TITLE
new dataset to load

### ISSUE THREAD

**Issue by samuelpayne** [PayneLab/covid19pandas#1]
please also add the time series in addition to the simple total counts

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by caleb-lindgren** [comment]
We actually are including the time series. The files you linked are the ones the package downloads. I don't think we're giving total counts, unless you sum it up yourself. Could you show me the code that's giving you just total counts?

**Comment by caleb-lindgren** [comment]
Closing issue--question has been resolved. Our package is returning time series.
